### ISSUE TITLE
Problem with Check command for IBM i.

### ISSUE THREAD

**Issue by ChrisHird** [NEMSLinux/nems-admin#8]
Does not run, the following is the output.
Problem with the check_ibmi_disk. cannot find the class.
(No output on stdout) stderr: java.lang.ClassNotFoundException: com.ibm.nagios.service.impl.DiskUtiliz
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:315)
    at com.ibm.nagios.util.ActionFactory.get(ActionFactory.java:13)
    at com.ibm.nagios.client.CheckIBMiStatus.main(CheckIBMiStatus.java:49)
java.lang.NullPointerException
    at com.ibm.nagios.client.CheckIBMiStatus.main(CheckIBMiStatus.java:73)

**Comment by NEMSLinux** [comment]
Noting your post here for future review: https://github.com/IBM/nagios-for-i/issues/17

**Comment by NEMSLinux** [comment]
Moved to correct repository: https://github.com/NEMSLinux/nems-plugins/issues/14
